node_types:

  application.nodes.MongoDatabase:
    derived_from: cloudify.nodes.DBMS
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path:
              default: scripts/mongo/install-mongo.sh
            fabric_env:
              default:
                host_string: { get_input: mongodb_host }
                user: { get_input: mongo_agent_user }
                key_filename: { get_input: mongo_key_filename }
        start:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path:
              default: scripts/mongo/start-mongo.sh
            fabric_env:
              default:
                host_string: { get_input: mongodb_host }
                user: { get_input: mongo_agent_user }
                key_filename: { get_input: mongo_key_filename }
        stop:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path:
              default: scripts/mongo/stop-mongo.sh
            fabric_env:
              default:
                host_string: { get_input: mongodb_host }
                user: { get_input: mongo_agent_user }
                key_filename: { get_input: mongo_key_filename }

  application.nodes.NodeJSServer:
    derived_from: cloudify.nodes.ApplicationServer
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path:
              default: scripts/nodejs/install-nodejs.sh
            fabric_env:
              default:
                host_string: { get_input: nodejs_host }
                user: { get_input: nodejs_agent_user }
                key_filename: { get_input: nodejs_key_filename }

  application.nodes.ApplicationModule:
    derived_from: cloudify.nodes.ApplicationModule
    properties:
      application_url:
        description: >
        default: https://github.com/paypal/rest-api-sample-app-nodejs/archive/master.tar.gz
      startup_script:
        type: string
        default: app.js
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path:
              default: scripts/nodecellar/configure-nodecellar-app.sh
            fabric_env:
              default:
                host_string: { get_input: nodejs_host }
                user: { get_input: nodejs_agent_user }
                key_filename: { get_input: nodejs_key_filename }
        start:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path:
              default: scripts/nodecellar/start-nodecellar-app.sh
            fabric_env:
              default:
                host_string: { get_input: nodejs_host }
                user: { get_input: nodejs_agent_user }
                key_filename: { get_input: nodejs_key_filename }
        configure:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path:
              default: scripts/nodecellar/install-nodecellar-app.sh
            fabric_env:
              default:
                host_string: { get_input: nodejs_host }
                user: { get_input: nodejs_agent_user }
                key_filename: { get_input: nodejs_key_filename }
        stop:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path:
              default: scripts/nodecellar/stop-nodecellar-app.sh
            fabric_env:
              default:
                host_string: { get_input: nodejs_host }
                user: { get_input: nodejs_agent_user }
                key_filename: { get_input: nodejs_key_filename }

relationships:

  app_connected_to_mongo:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
       cloudify.interfaces.relationship_lifecycle:
          postconfigure:
           implementation: fabric.fabric_plugin.tasks.run_script
           inputs:
             script_path:
               default: scripts/mongo/set-mongo-url.sh
             fabric_env:
               default:
                 host_string: { get_input: nodejs_host }
                 user: { get_input: nodejs_agent_user }
                 key_filename: { get_input: nodejs_key_filename }

  app_contained_in_nodejs:
     derived_from: cloudify.relationships.connected_to
     source_interfaces:
        cloudify.interfaces.relationship_lifecycle:
           preconfigure:
            implementation: fabric.fabric_plugin.tasks.run_script
            inputs:
              script_path:
                default: scripts/nodejs/set-nodejs-root.sh
              fabric_env:
                default:
                  host_string: { get_input: nodejs_host }
                  user: { get_input: nodejs_agent_user }
                  key_filename: { get_input: nodejs_key_filename }
